---
- name: Install packages via APT
  apt: name={{ item }}
       update_cache=yes
       state=present
  with_items: "{{ apt_packages }}"

#- name: Install package via PIP
#  pip: name={{ item }}
#       state=present
#  with_items: "{{ pip_packages }}"
